version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9-browsers
    working_directory: ~/CircleCIGithubJS
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          command: |
            export APPLITOOLS_BATCH_ID=${CIRCLE_SHA1}
            echo $APPLITOOLS_BATCH_ID
            echo $APPLITOOLS_BASELINE_BRANCH
            echo $APPLITOOLS_BASELINE_BRANCH_NAME
            echo $APPLITOOLS_BASELINE_BRANCH
            echo $APPLITOOLS_BRANCH_BASELINE
            echo $APPLITOOLS_BRANCH_BASELINE_NAME
            npm test